overrides:
  lighthouse: 13.4.1
  qs: 6.16.0
  tmp: 0.2.7
  uuid: 11.1.1
  "@lhci/cli@0.15.1>proxy-agent": 6.5.0

allowBuilds:
  esbuild: true
  sharp: false

minimumReleaseAgeExclude:
  - '@astrojs/markdown-satteri@0.4.1'
  - astro@7.3.2
